name: upload artifact
on: push
jobs:
    artifact:
       runs-on: ubuntu-latest
       steps:
        - name: checkout
          uses: actions/checkout@v4
        - name:  install cowsay program
          run: sudo apt-get install cowsay -y

        - name: Execute cowsay CMD
          run: cowsay -f dragon "Run for cover, iam a Dragon....RAWR" >> dragon.txt

        - name: upload artifact 
          uses: actions/upload-artifact@v4.3.4
          with:
            name: dragon-file
            path: dragon.txt
    download_file:
        runs-on: ubuntu-latest
        needs:  artifact
        steps:
            - name: download
              uses: actions/download-artifact@v4
              with:
                name: dragon-file
            - name: test file
              run: grep -i "dragon" dragon.txt
    build_job2:
        runs-on: ubuntu-latest
        needs:   download_file
        steps:
            - name: download
              uses: actions/download-artifact@v4
              with:
                name: dragon-file
            - name: Read file
              run:  cat dragon.txt   
            - name: Deploy
              run: echo Deploying...........       
              

    

