name: first
on: push
jobs:
    first:
        runs-on: ubuntu:latest
        steps:



            - name: list files
              run: ls -ltra
            - name: run shell
              run:
                chmod +x script.sh
                ./script.sh


